<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Advanced Search' => 'Erweiterte Suche',
    'All' => 'Alle',
    'Alternative Text' => 'Alternativer Text',
    'Browse' => 'Durchsuchen',
    'Cancel' => 'Abbrechen',
    'Category' => 'Kategorie',
    'Click a file to view info.' => 'Klicke eine Datei, um Infos zu erhalten',
    'Click {link} to create a folder to upload media' => 'Klicke {link} um einen Ordner für Dateien zu erstellen',
    'Confirm delete {src_file_name} ?' => 'Löschen von {src_file_name} bestätigen?',
    'Copy' => 'Kopiere',
    'Create Folder' => 'Ordner erstellen',
    'Created At' => 'Erstellt am',
    'Delete' => 'Löschen',
    'Delete Permanently' => 'Vollständig löschen',
    'Description' => 'Beschreibung',
    'Dimension' => 'Dimensionen',
    'Edit' => 'Bearbeiten',
    'Enter or select tags...' => 'Tags eingeben oder wählen...',
    'Fail to create thumbnail.' => 'Vorschaubild konnte nichst erstellt werden',
    'File ID' => 'Dateikennung',
    'File Identifier' => 'Dateibezeichnung',
    'File Name' => 'Dateiname',
    'File dimension at most 2272 X 1704.' => 'Dateidimensionen maximal 2272 x 1704.',
    'File not found.' => 'Datei nicht gefunden.',
    'Filename can only contain alphanumeric characters, underscores and dashes.' => 'Der Dateiname darf nur alphanumerische Zeichen, sowie Grundstriche und Gedankenstriche enthalten',
    'Folder ID' => 'Ordnerkennung',
    'Invalid file extension. Available file extension are {ext}' => 'Unzulässige Dateiendung. Mögliche Dateien sind {ext}',
    'Invalid file type. Available file types are {types}' => 'Unzulässiger Dateityp. Mögliche Dateien sind {types}',
    'Invalid folder location.' => 'Unzulässiger Ordnerpfad',
    'Invalid value: {variable}' => 'Unzulässiger Wert: {variable}',
    'Library' => 'Bibliothek',
    'Limit is {limit}MB' => 'Das Limit liegt bei {limit}MB',
    'Media Folder' => 'Medienordner',
    'Media Gallery' => 'Mediengallerie',
    'Media Property' => 'Medieneigenschaft',
    'Mime Type' => 'MIME Typ',
    'Object Url' => 'URL der Datei',
    'Path' => 'Pfad',
    'Remove' => 'Entfernen',
    'Search' => 'Suchen',
    'Search by File Name, Title, Alternative Text or Description...' => 'Suche nach Dateinamen, Titel, Alternativer Text oder Beschreibung',
    'Search by tag...' => 'Suche nach Tag...',
    'Storage' => 'Speicherung',
    'Storage ID' => 'Speicherkennung',
    'Tag ID' => 'Tag Kennung',
    'Tags' => 'Tags',
    'This {attribute} already been taken.' => 'Die Eigenschaft {attribute} wurde schon verwendet.',
    'Thumbnail File Name' => 'Name des Vorschaubildes',
    'Title' => 'Titel',
    'Update' => 'Aktualisieren',
    'Updated At' => 'Aktualisiert am',
    'Upload New' => 'Neue hochladen',
    'Upload New Media' => 'Neue Datei hochladen',
    'Upload To' => 'Hochladen nach',
    'Upload fail due to some reasons.' => 'Das Hochladen ist fehlgeschlagen',
    'Url' => 'URL',
    'Use' => 'Benutzer',
    'Value' => 'Wert',
    'View' => 'Ansicht',
    'here' => 'hier',
    'host' => 'Anbieter',
    'Create' => 'Erstellen',
    'Keywords' => 'Schlüsselwörter'
];
